services:
  back:
    container_name: "djangogramm"
    platform: "linux/amd64"
    build:
      context: "./"
      dockerfile: "./dockerfiles/Dockerfile.app"
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    volumes:
      - ./djangogramm:/app
    restart: always
    # command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - DEBUG=True
      - DB_HOST=db-djangogramm
      - DB_PORT=5432
      - PYTHONPATH=/app:$PYTHONPATH
    depends_on:
      - db-djangogramm

  db-djangogramm:
    image: postgres:15.3-bullseye
    container_name: Postgres-djangogramm
    restart: always
    environment:
      # POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: djangogramm
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer-djangogramm:
    image: adminer
    container_name: Adminer-djangogramm
    restart: always
    ports:
      - 8080:8080